### ISSUE TITLE
[Crash] Crash on Start up

### ISSUE THREAD

**Issue by A5ho9999** [ACgamerReal/The-Chocolate-Mod-Expanded-Sources#4]
Minecraft: 1.20.1
Fabric Loader 0.15.7
Mod Version [8.0](https://modrinth.com/mod/the-chocolate-mod/version/8.0)

Probably due to the fact most 1.20.3+ version won't work on 1.20.1, but still figured would report it

```
Time: 2024-02-24 14:55:56
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'scme'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2349.<init>(net.minecraft.class_4719, net.minecraft.class_4970$class_2251)'
	at net.scme.block.ModBlocks.<clinit>(ModBlocks.java:46)
	at net.scme.SCME.onInitialize(SCME.java:69)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
```

**Comment by ACgamerReal** [comment]
Ah I see, I can't really do anything significant about this so I'll change the versions names available to 1.20.2, .3 and .4

Thanks for reporting it tho!
